#!/usr/bin/env python3
# Gera po/en.po a partir de po/procforge.pot aplicando o dicionário T (pt -> en).
# Usa o .pot como fonte da verdade dos msgids (garante casamento exato).
import sys

def unescape(s):
    out = []; i = 0
    while i < len(s):
        c = s[i]
        if c == '\\' and i + 1 < len(s):
            n = s[i+1]
            out.append({'n':'\n','t':'\t','r':'\r','"':'"','\\':'\\'}.get(n, n)); i += 2
        else:
            out.append(c); i += 1
    return ''.join(out)

def escape(s):
    return s.replace('\\','\\\\').replace('"','\\"').replace('\n','\\n').replace('\t','\\t')

def parse_ids(path):
    ids = []; cur = None; mode = None
    for line in open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        if line.startswith('msgid '):
            if cur is not None: ids.append(cur)
            cur = unescape(line[6:].strip()[1:-1]); mode = 'id'
        elif line.startswith('msgstr'):
            mode = 'str'
        elif line.startswith('"'):
            if mode == 'id': cur += unescape(line.strip()[1:-1])
        # comentários e linhas em branco: ignora
    if cur is not None: ids.append(cur)
    return [x for x in ids if x]

T = {
    " % de um núcleo (0 = sem limite)": " % of one core (0 = no limit)",
    " MB (0 = sem limite)": " MB (0 = no limit)",
    " s": " s",
    "%1  (%2 processos)": "%1  (%2 processes)",
    "%1 (PID %2)": "%1 (PID %2)",
    "%1 byte(s) gravado(s).": "%1 byte(s) written.",
    "%1 processo(s) da árvore encerrado(s).": "%1 process(es) of the tree terminated.",
    "%1 resultado(s) para \"%2\"": "%1 result(s) for \"%2\"",
    "%1 resultados": "%1 results",
    "%1 resultados (mostrando %2)": "%1 results (showing %2)",
    "%1+ resultados (truncado — refine mais)": "%1+ results (truncated — refine further)",
    "&Ferramentas": "&Tools",
    "&Hacker": "&Hacker",
    "&Usuários": "&Users",
    "&Ver": "&View",
    "(sem dados)": "(no data)",
    "0 resultados": "0 results",
    "0,5 s": "0.5 s",
    "1 s": "1 s",
    "2 s": "2 s",
    "5 s": "5 s",
    "< valor": "< value",
    "<falha ao ler — endereço não mapeado ou sem permissão>": "<failed to read — address not mapped or no permission>",
    "= valor": "= value",
    "> valor": "> value",
    "Afinidade de CPU — %1 (PID %2)": "CPU affinity — %1 (PID %2)",
    "Afinidade de CPU...": "CPU affinity...",
    "Aj&uda": "&Help",
    "Alvo": "Target",
    "Alvo inválido.": "Invalid target.",
    "Arquivo mapeado": "Mapped file",
    "Arquivos abertos": "Open files",
    "Ativa": "Active",
    "Atualizar": "Refresh",
    "Automático (sistema)": "Automatic (system)",
    "Autorização negada pelo polkit.": "Authorization denied by polkit.",
    "Base": "Base",
    "Batch": "Batch",
    "Biblioteca injetada (handle 0x%1).": "Library injected (handle 0x%1).",
    "Biblioteca injetada via helper.": "Library injected via helper.",
    "Bibliotecas / Mapas": "Libraries / Maps",
    "Bibliotecas compartilhadas (*.so *.so.*)": "Shared libraries (*.so *.so.*)",
    "Buscar em fds e bibliotecas mapeadas (nome de arquivo, socket:[inode], .so):": "Search fds and mapped libraries (file name, socket:[inode], .so):",
    "Buscar processos (Ctrl+K)": "Search processes (Ctrl+K)",
    "Bytes (hex):": "Bytes (hex):",
    "Bytes hex inválidos (ex.: de ad be ef).": "Invalid hex bytes (e.g.: de ad be ef).",
    "Bytes privados": "Private bytes",
    "Bytes:": "Bytes:",
    "CPU": "CPU",
    "CPU %1": "CPU %1",
    "CPU:": "CPU:",
    "CPU: %1%": "CPU: %1%",
    "CPUs permitidas": "Allowed CPUs",
    "Carregada": "Loaded",
    "Claro": "Light",
    "Classe de I/O:": "I/O class:",
    "Clássico (Process Hacker)": "Classic (Process Hacker)",
    "Compartilha todos os namespaces com você (mesmo ambiente).": "Shares all namespaces with you (same environment).",
    "Compartilhado com você?": "Shared with you?",
    "Conexões TCP": "TCP connections",
    "Congelados (reescritos em loop):": "Frozen (rewritten in a loop):",
    "Congelar →": "Freeze →",
    "Copia o fd para este processo via pidfd_getfd.": "Copies the fd into this process via pidfd_getfd.",
    "Copiar PID": "Copy PID",
    "Descongelar": "Unfreeze",
    "Descritores": "Descriptors",
    "Descrição": "Description",
    "Digite um valor para buscar.": "Type a value to search for.",
    "Disco": "Disk",
    "Dispositivo": "Device",
    "Dormindo": "Sleeping",
    "Duplicar p/ mim": "Duplicate to me",
    "Duração:": "Duration:",
    "Editar valor em 0x%1": "Edit value at 0x%1",
    "Editar valor...": "Edit value...",
    "Endereço": "Address",
    "Endereço (hex):": "Address (hex):",
    "Endereço inválido.": "Invalid address.",
    "Enviar sinal": "Send signal",
    "Erro: %1": "Error: %1",
    "Escalonamento aplicado a %1.": "Scheduling applied to %1.",
    "Escalonamento avançado...": "Advanced scheduling...",
    "Escalonamento — %1 (PID %2)": "Scheduling — %1 (PID %2)",
    "Escolher biblioteca para injetar": "Choose a library to inject",
    "Escrever bytes": "Write bytes",
    "Escrever na memória": "Write to memory",
    "Escrita/s": "Write/s",
    "Escrito (total)": "Written (total)",
    "Escuro": "Dark",
    "Espera ininterrupta (D)": "Uninterruptible sleep (D)",
    "Estado": "State",
    "Executando": "Running",
    "Executar": "Run",
    "Executar...": "Run...",
    "Expandir tudo": "Expand all",
    "FD": "FD",
    "Falha ao ajustar prioridade (nice %1): %2": "Failed to set priority (nice %1): %2",
    "Falha ao definir afinidade: %1": "Failed to set affinity: %1",
    "Falha ao definir escalonador: %1": "Failed to set scheduler: %1",
    "Falha ao definir limite: %1": "Failed to set limit: %1",
    "Falha ao definir prioridade de I/O: %1": "Failed to set I/O priority: %1",
    "Falha ao enviar sinal: %1": "Failed to send signal: %1",
    "Falha ao escrever na memória (permissão?).": "Failed to write to memory (permission?).",
    "Falha ao gravar (permissão?).": "Failed to write (permission?).",
    "Faça a primeira busca antes de refinar.": "Do the first scan before refining.",
    "Fechar descritor alheio": "Close another process's descriptor",
    "Fechar janela": "Close window",
    "Fechar no dono": "Close in owner",
    "Flags": "Flags",
    "GETREGSET falhou: %1": "GETREGSET failed: %1",
    "Gravar": "Write",
    "Gravar %1 byte(s) em 0x%2 do processo %3?": "Write %1 byte(s) at 0x%2 of process %3?",
    "Hard ('ilimitado' ou número):": "Hard ('unlimited' or number):",
    "Helper privilegiado não instalado. Rode: ./install-helper.sh": "Privileged helper not installed. Run: ./install-helper.sh",
    "I/O total": "I/O total",
    "I/O: Melhor esforço": "I/O: Best effort",
    "I/O: Nenhuma": "I/O: None",
    "I/O: Ocioso": "I/O: Idle",
    "I/O: Tempo real": "I/O: Real time",
    "Idioma": "Language",
    "Idioma / Language": "Language / Idioma",
    "Informação do sistema": "System information",
    "Informação do sistema...": "System information...",
    "Iniciar": "Start",
    "Injeta close() no processo alvo (libera a trava).": "Injects close() into the target process (releases the lock).",
    "Injetar": "Inject",
    "Injetar biblioteca": "Inject library",
    "Injetar biblioteca (.so)...": "Inject library (.so)...",
    "Injetar close(%1) no processo %2 (%3)?\n\nAlvo: %4\n\nIsto libera a trava mantida por este fd (lockfile, socket do singleton, eventfd) sem matar o processo. A operação usa ptrace.":
        "Inject close(%1) into process %2 (%3)?\n\nTarget: %4\n\nThis releases the lock held by this fd (lockfile, singleton socket, eventfd) without killing the process. The operation uses ptrace.",
    "Injetar '%1' em %2 (PID %3) forçando dlopen via ptrace?\n\nIsto EXECUTA CÓDIGO dentro do processo alvo e pode travá-lo se a biblioteca for incompatível. Use só em processos que você controla.":
        "Inject '%1' into %2 (PID %3) forcing dlopen via ptrace?\n\nThis EXECUTES CODE inside the target process and may crash it if the library is incompatible. Use only on processes you control.",
    "Inode": "Inode",
    "Intervalo de atualização": "Update interval",
    "Isolado em %1 namespace(s) — provável container/sandbox.": "Isolated in %1 namespace(s) — likely container/sandbox.",
    "Janela": "Window",
    "Kernel: %1\nDistribuição: %2\nCPU: %3 (%4 núcleos)\nMemória: %5 usada de %6\nCarga (1/5/15 min): %7\nUptime: %8":
        "Kernel: %1\nDistribution: %2\nCPU: %3 (%4 cores)\nMemory: %5 used of %6\nLoad (1/5/15 min): %7\nUptime: %8",
    "Leitura/s": "Read/s",
    "Ler": "Read",
    "Ler memória": "Read memory",
    "Lido (total)": "Read (total)",
    "Limitar recursos (cgroup)...": "Limit resources (cgroup)...",
    "Limitar recursos — %1 (PID %2)": "Limit resources — %1 (PID %2)",
    "Limite aplicado a %1.": "Limit applied to %1.",
    "Limites (prlimit) — %1 (PID %2)": "Limits (prlimit) — %1 (PID %2)",
    "Limites (prlimit)...": "Limits (prlimit)...",
    "Limites aplicados a %1 (PID %2) via cgroup.": "Limits applied to %1 (PID %2) via cgroup.",
    "Limites removidos de %1 (PID %2).": "Limits removed from %1 (PID %2).",
    "Local": "Local",
    "Localizar handles ou DLLs": "Find handles or DLLs",
    "Localizar handles ou DLLs...": "Find handles or DLLs...",
    "Matar %1 (PID %2) e TODA a sua descendência com SIGKILL?": "Kill %1 (PID %2) and ALL its descendants with SIGKILL?",
    "Matar árvore": "Kill tree",
    "Matar árvore inteira": "Kill entire tree",
    "Memória (hex)": "Memory (hex)",
    "Memória física: %1 (%2%)": "Physical memory: %1 (%2%)",
    "Memória máx.:": "Max memory:",
    "Minimizar": "Minimize",
    "Modo:": "Mode:",
    "Morto": "Dead",
    "Máx. de PIDs:": "Max PIDs:",
    "Namespace": "Namespace",
    "Namespaces / containers...": "Namespaces / containers...",
    "Namespaces — %1 (PID %2)": "Namespaces — %1 (PID %2)",
    "Nenhum processo selecionado": "No process selected",
    "Nome": "Name",
    "Normal (OTHER)": "Normal (OTHER)",
    "Nova busca": "New scan",
    "Novo valor (%1):": "New value (%1):",
    "NÃO (isolado)": "NO (isolated)",
    "Não consegui iniciar: %1": "Could not start: %1",
    "Não consegui ler o valor atual.": "Could not read the current value.",
    "O PID %1 foi reutilizado por outro processo.": "PID %1 was reused by another process.",
    "O alvo não parou como esperado.": "The target did not stop as expected.",
    "O idioma muda ao reiniciar o ProcForge. Reiniciar agora?": "The language changes when ProcForge restarts. Restart now?",
    "O processo %1 não existe mais.": "Process %1 no longer exists.",
    "Ocioso (IDLE)": "Idle (IDLE)",
    "Ocioso (kernel)": "Idle (kernel)",
    "Offset": "Offset",
    "Opções": "Options",
    "Opções: use o menu Ver › Intervalo de atualização.": "Options: use the View › Update interval menu.",
    "PEEKTEXT falhou: %1": "PEEKTEXT failed: %1",
    "PID": "PID",
    "POKETEXT falhou: %1": "POKETEXT failed: %1",
    "PTRACE_INTERRUPT falhou: %1": "PTRACE_INTERRUPT failed: %1",
    "PTRACE_SEIZE falhou: %1": "PTRACE_SEIZE failed: %1",
    "Parado (stopped)": "Stopped",
    "Parar": "Stop",
    "Perms": "Perms",
    "Política:": "Policy:",
    "Primeira busca": "First scan",
    "Principal": "Main",
    "Prioridade (nice)...": "Priority (nice)...",
    "Prioridade RT (FIFO/RR):": "RT priority (FIFO/RR):",
    "Prioridade de %1 (PID %2)": "Priority of %1 (PID %2)",
    "Prioridade de I/O (0-7):": "I/O priority (0-7):",
    "Processo": "Process",
    "Processos": "Processes",
    "Processos: %1": "Processes: %1",
    "Programa e argumentos:": "Program and arguments:",
    "Proto": "Proto",
    "Rastreado (traced)": "Traced",
    "Rastreamento eBPF — %1 (PID %2)": "eBPF tracing — %1 (PID %2)",
    "Rastrear": "Trace",
    "Rastrear com eBPF...": "Trace with eBPF...",
    "Recolher tudo": "Collapse all",
    "Recurso:": "Resource:",
    "Recusado: não vou matar o PID %1.": "Refused: I won't kill PID %1.",
    "Rede": "Network",
    "Refinar": "Refine",
    "Reiniciar": "Restart",
    "Remoto": "Remote",
    "Remover limites (cgroup)": "Remove limits (cgroup)",
    "Restaurar": "Restore",
    "Resultados para \"%1\"": "Results for \"%1\"",
    "Retomar (CONT)": "Resume (CONT)",
    "Retomar thread": "Resume thread",
    "Rodar dentro (mnt/net/ipc/uts/cgroup):": "Run inside (mnt/net/ipc/uts/cgroup):",
    "SETREGSET falhou: %1": "SETREGSET failed: %1",
    "SINGLESTEP falhou: %1": "SINGLESTEP failed: %1",
    "Sair": "Quit",
    "Scanner": "Scanner",
    "Scanner de memória — %1 (PID %2)": "Memory scanner — %1 (PID %2)",
    "Scanner de memória...": "Memory scanner...",
    "Selecione ao menos uma CPU.": "Select at least one CPU.",
    "Selecione um descritor primeiro.": "Select a descriptor first.",
    "Selecione um resultado para congelar.": "Select a result to freeze.",
    "Selecione um resultado.": "Select a result.",
    "Sem permissão para ler a memória deste processo (uid diferente). A busca direta funciona para processos do seu usuário; varredura cross-uid pelo helper é um passo futuro.":
        "No permission to read this process's memory (different uid). Direct scanning works for your own processes; cross-uid scanning via the helper is a future step.",
    "Serviços": "Services",
    "Sistema (Breeze)": "System (Breeze)",
    "Sobre o ProcForge": "About ProcForge",
    "Soft ('ilimitado' ou número):": "Soft ('unlimited' or number):",
    "Sub": "Sub",
    "Suspender (STOP)": "Suspend (STOP)",
    "Suspender thread": "Suspend thread",
    "Suspender uma thread isolada é suportado apenas para processos do seu usuário (o tracer ptrace vive dentro da GUI).":
        "Suspending an individual thread is supported only for your own processes (the ptrace tracer lives inside the GUI).",
    "Suspensa": "Suspended",
    "Syscalls (contagem)": "Syscalls (count)",
    "Só bibliotecas (.so)": "Libraries only (.so)",
    "TID": "TID",
    "Tamanho": "Size",
    "Tema": "Theme",
    "Tempo real FIFO": "Real time FIFO",
    "Tempo real RR": "Real time RR",
    "Terminar": "Terminate",
    "Terminar o processo selecionado (SIGTERM)": "Terminate the selected process (SIGTERM)",
    "Threads (suspender/retomar)...": "Threads (suspend/resume)...",
    "Threads — %1 (PID %2)": "Threads — %1 (PID %2)",
    "Tipo": "Type",
    "Tipo:": "Type:",
    "Trazer para frente": "Bring to front",
    "Unidade": "Unit",
    "Usuário": "User",
    "Valor": "Value",
    "Valor inválido para o tipo %1.": "Invalid value for type %1.",
    "Valor travado": "Locked value",
    "Valor:": "Value:",
    "Zumbi": "Zombie",
    "aumentou": "increased",
    "close(%1) executado no alvo (retorno %2).": "close(%1) executed in target (return %2).",
    "close() no alvo falhou: %1": "close() in target failed: %1",
    "diminuiu": "decreased",
    "executando (via helper, com polkit)...": "running (via helper, with polkit)...",
    "fd %1 (%2)": "fd %1 (%2)",
    "fd %1 duplicado para nós via pidfd_getfd (fd local %2). O fd do dono continua aberto.":
        "fd %1 duplicated to us via pidfd_getfd (local fd %2). The owner's fd stays open.",
    "mapa": "map",
    "mudou": "changed",
    "nice (-20 = mais prioritário, 19 = menos):": "nice (-20 = highest priority, 19 = lowest):",
    "não mudou": "unchanged",
    "pidfd_getfd falhou: %1": "pidfd_getfd failed: %1",
    "pidfd_open falhou: %1": "pidfd_open failed: %1",
    "rastreando %1 s com eBPF (roda no helper como root)...": "tracing %1 s with eBPF (runs in the helper as root)...",
    "sem limite": "no limit",
    "sim": "yes",
    "Opções...": "Options...",
    "Intervalo de atualização:": "Update interval:",
    "Atualização em tempo real (eventos cn_proc via helper)": "Real-time updates (cn_proc events via helper)",
    "Tema:": "Theme:",
    "Idioma / Language:": "Language / Idioma:",
    " MB/s (0 = sem limite)": " MB/s (0 = no limit)",
    "Máx. I/O de disco:": "Max disk I/O:",
    "Matar processo (SIGTERM)": "Kill process (SIGTERM)",
    "Matar processo (SIGKILL)": "Kill process (SIGKILL)",
    "Processo %1 não está na lista.": "Process %1 is not in the list.",
    "Ativação": "Startup",
    "Recarregar": "Reload",
    "Habilitar (no boot)": "Enable (on boot)",
    "Desabilitar (no boot)": "Disable (on boot)",
    "Mascarar": "Mask",
    "Desmascarar": "Unmask",
    "Status / journal...": "Status / journal...",
    "Ir para o processo": "Go to process",
    "Status — %1": "Status — %1",
    "(sem saída)": "(no output)",
    "O serviço %1 não tem processo principal em execução.": "Service %1 has no running main process.",
    "Fechar esta conexão (ss -K)": "Close this connection (ss -K)",
    "Não consegui montar o filtro da conexão.": "Could not build the connection filter.",
    "Propriedades...": "Properties...",
    "Propriedades — %1 (PID %2)": "Properties — %1 (PID %2)",
    "<b>%1</b> (PID %2)": "<b>%1</b> (PID %2)",
    "Geral": "General",
    "Estatísticas": "Statistics",
    "Threads": "Threads",
    "Token": "Token",
    "Ambiente": "Environment",
    "Handles": "Handles",
    "Memória": "Memory",
    "PID pai": "Parent PID",
    "Iniciado": "Started",
    "Executável": "Executable",
    "Diretório de trabalho": "Working directory",
    "Raiz (chroot)": "Root (chroot)",
    "Linha de comando": "Command line",
    "Nice": "Nice",
    "Afinidade de CPU": "CPU affinity",
    "Métrica": "Metric",
    "real %1 · efetivo %2 · salvo %3 · fs %4": "real %1 · effective %2 · saved %3 · fs %4",
    "UID": "UID",
    "GID": "GID",
    "Grupos": "Groups",
    "Capabilities efetivas": "Effective capabilities",
    "Capabilities permitidas": "Permitted capabilities",
    "Capabilities herdáveis": "Inheritable capabilities",
    "Capabilities do bounding set": "Bounding set capabilities",
    "Capabilities ambientais": "Ambient capabilities",
    "Seccomp": "Seccomp",
    "filtro (BPF)": "filter (BPF)",
    "estrito": "strict",
    "desativado": "disabled",
    "NoNewPrivs": "NoNewPrivs",
    "não": "no",
    "Contexto de segurança": "Security context",
    "Variável": "Variable",
    "Sem permissão para ler o ambiente (uid diferente).": "No permission to read the environment (different uid).",
    "Arquivo": "File",
    "Tempo de CPU (usuário)": "CPU time (user)",
    "Tempo de CPU (sistema)": "CPU time (system)",
    "Memória (RSS)": "Memory (RSS)",
    "Memória virtual": "Virtual memory",
    "Dados/heap": "Data/heap",
    "Pilha": "Stack",
    "Swap": "Swap",
    "Disco lido": "Disk read",
    "Disco escrito": "Disk written",
    "Trocas de contexto (voluntárias)": "Context switches (voluntary)",
    "Trocas de contexto (involuntárias)": "Context switches (involuntary)",
    "  [suspensa]": "  [suspended]",
    "ProcForge — clone do Process Hacker para Linux.\n\nManipulação ativa do sistema sobre primitivas nativas: procfs, pidfd, ptrace, process_vm_readv/writev, cgroups v2, netlink, eBPF, KWin, com helper D-Bus privilegiado e polkit por ação.\n\nQt6 · KDE Frameworks 6 · Wayland.":
        "ProcForge — a Process Hacker clone for Linux.\n\nActive system manipulation over native primitives: procfs, pidfd, ptrace, process_vm_readv/writev, cgroups v2, netlink, eBPF, KWin, with a privileged D-Bus helper and per-action polkit.\n\nQt6 · KDE Frameworks 6 · Wayland.",
}

ids = parse_ids('po/procforge.pot')
missing = []
with open('po/en.po', 'w', encoding='utf-8') as f:
    f.write('msgid ""\nmsgstr ""\n"Content-Type: text/plain; charset=UTF-8\\n"\n"Language: en\\n"\n\n')
    for m in ids:
        tr = T.get(m)
        if tr is None:
            missing.append(m); tr = ''
        f.write('msgid "%s"\nmsgstr "%s"\n\n' % (escape(m), escape(tr)))

print("total msgids:", len(ids), " traduzidos:", len(ids) - len(missing), " faltando:", len(missing))
for m in missing:
    print("  FALTA:", repr(m))
